// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct MovieList: Codable {
    public var page: Int
    public var results: [Result]?
    public var totalPages: Int

    public struct Result: Codable {
        public var id: Int

        public init(id: Int) {
            self.id = id
        }

        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: StringCodingKey.self)
            self.id = try values.decode(Int.self, forKey: "id")
        }

        public func encode(to encoder: Encoder) throws {
            var values = encoder.container(keyedBy: StringCodingKey.self)
            try values.encode(id, forKey: "id")
        }
    }

    public init(page: Int, results: [Result]? = nil, totalPages: Int) {
        self.page = page
        self.results = results
        self.totalPages = totalPages
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.page = try values.decode(Int.self, forKey: "page")
        self.results = try values.decodeIfPresent([Result].self, forKey: "results")
        self.totalPages = try values.decode(Int.self, forKey: "total_pages")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(page, forKey: "page")
        try values.encodeIfPresent(results, forKey: "results")
        try values.encode(totalPages, forKey: "total_pages")
    }
}
