// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct TMDBError: Codable {
    public var statusMessage: String?
    public var statusCode: Int?

    public init(statusMessage: String? = nil, statusCode: Int? = nil) {
        self.statusMessage = statusMessage
        self.statusCode = statusCode
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.statusMessage = try values.decodeIfPresent(String.self, forKey: "status_Message")
        self.statusCode = try values.decodeIfPresent(Int.self, forKey: "status_Code")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(statusMessage, forKey: "status_Message")
        try values.encodeIfPresent(statusCode, forKey: "status_Code")
    }
}
