// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Search {
    public var movie: Movie {
        Movie(path: path + "/movie")
    }

    public struct Movie {
        /// Path: `/search/movie`
        public let path: String

        /// Search movies
        ///
        /// Returns searched movies
        public func get(parameters: GetParameters) -> Request<TMDBClient.MovieList> {
            Request(method: "GET", url: path, query: parameters.asQuery, id: "searchMovie")
        }

        public struct GetParameters {
            public var page: Int?
            public var language: String?
            public var query: String

            public init(page: Int? = nil, language: String? = nil, query: String) {
                self.page = page
                self.language = language
                self.query = query
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(page, forKey: "page")
                encoder.encode(language, forKey: "language")
                encoder.encode(query, forKey: "query")
                return encoder.items
            }
        }
    }
}
