// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var movie: Movie {
        Movie(path: "/movie")
    }

    public struct Movie {
        /// Path: `/movie`
        public let path: String
    }
}
