// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Movie {
    public var popular: Popular {
        Popular(path: path + "/popular")
    }

    public struct Popular {
        /// Path: `/movie/popular`
        public let path: String

        /// Finds popular movies
        ///
        /// Returns 20 popular movies
        public func get(page: Int? = nil, language: String? = nil) -> Request<TMDBClient.MovieList> {
            Request(method: "GET", url: path, query: makeGetQuery(page, language), id: "getPopularMovies")
        }

        private func makeGetQuery(_ page: Int?, _ language: String?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(page, forKey: "page")
            encoder.encode(language, forKey: "language")
            return encoder.items
        }
    }
}
